name: Build Frida Gadget (.so) for Android

on: [push]

jobs:
  build-gadget:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [android-arm, android-arm64, android-x86, android-x86_64]

    env:
      FRIDA_PREFIX: ${{ runner.temp }}/frida-install

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git build-essential
          pip3 install meson ninja

      - name: Download Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d $HOME/android-ndk
        env:
          ANDROID_NDK_HOME: $HOME/android-ndk/android-ndk-r25c

      - name: Set up environment
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25c" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Bootstrap Frida toolchain
        run: |
          python3 releng/deps.py install --devkit ${{ matrix.arch }}

      - name: Configure Frida build
        run: |
          ./configure \
            --prefix=$FRIDA_PREFIX \
            --host=${{ matrix.arch }} \
            --enable-gadget \
            --disable-python \
            --disable-node \
            --disable-csharp \
            --disable-qml

      - name: Build Frida Gadget
        run: |
          make -j$(nproc)
          make install

      - name: Upload frida-gadget.so
        uses: actions/upload-artifact@v4
        with:
          name: frida-gadget-${{ matrix.arch }}.so
          path: ${{ env.FRIDA_PREFIX }}/lib/frida/${{ matrix.arch }}/frida-gadget.so
